services:
  - type: web
    name: bladeio-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
